from matrixlib import Matrix
import math
import csv

class Neuron:
    def __init__(self, num_features: int):
        """
        Initialize the logistic regression model parameters.

        Args:
            num_features (int): The number of input variables.
        """
        self.W = Matrix(num_features, 1)
        self.W.randomize(-1.0, 1.0)
        self.bias = 0.0

    def sigmoid(self, value: float):
        """
        Compute the sigmoid activation for a single scalar value.
        """
        return 1.0 / (1.0 + math.exp(-value))

    def forward (self, X: Matrix) -> Matrix:
        """
        Execute the forward propagation pass.
        """
        Z = (X * self.W) + self.bias
        activation = Z.map(self.sigmoid)
        return activation
    
    def compute_loss(self, y_true: Matrix, y_pred: Matrix) -> float:
        """
        Compute the Binary Cross-Entropy loss.
        
        Args:
            y_true (Matrix): The actual expected values (0.0 or 1.0).
            y_pred (Matrix): The predicted probabilities generated by the forward pass.
            
        Returns:
            float: The calculated scalar loss value.
        """
        num_samples = y_true.rows
        epsilon = 1e-15
        loss_sum = 0.0

        for i in range (num_samples):
            y = y_true[i, 0]
            pred = y_pred[i, 0]
            pred = max(epsilon, min(1.0 - epsilon, pred))

            sample_loss = (y * math.log(pred)) + ((1.0 - y) * math.log(1.0 - pred))
            loss_sum += sample_loss
        return -(loss_sum / num_samples)

    def backward(self, X: Matrix, y_true: Matrix, y_pred: Matrix) -> tuple:
        """
        Compute gradients of the loss function with respect to weights (dW) and bias (db).
        
        Args:
            X (Matrix): The input data matrix.
            y_true (Matrix): The expected binary labels (0.0 or 1.0).
            y_pred (Matrix): The predicted probabilities.
            
        Returns:
            tuple: The weight gradients matrix (dW) and the bias gradient scalar (db).
        """
        num_samples = X.rows
        num_features = X.cols

        dW = Matrix(num_features, 1)
        db_sum = 0.0

        for i in range(num_samples):
            error = y_pred[i, 0] - y_true[i, 0]
            db_sum += error

        db = db_sum / num_samples

        for j in range(num_features):
            grad_sum = 0.0
            for i in range(num_samples):
                error = y_pred[i, 0] - y_true[i, 0]
                grad_sum += error * X[i, j]
            dW[j, 0] = grad_sum / num_samples
        return dW, db

    def update_parameters(self, dW: Matrix, db: float, learning_rate:float):
        """
        Update the model parameters using Gradient optimization.
        
        Args:
            dW (Matrix): The gradients of the weights.
            db (float): The gradient of the bias.
            learning_rate (float): The step size multiplier (alpha).
        """
        self.bias = self.bias - (learning_rate * db)
        num_features = self.W.rows
        
        for j in range(num_features):
            current_weight = self.W[j, 0]
            gradient = dW[j, 0]
            self.W[j, 0] = current_weight - (learning_rate * gradient)
